### ISSUE TITLE
奔溃crash

### ISSUE THREAD

**Issue by Jushua-bin** [Monocluar/UnLive2D#11]
这个怀疑是换live2d后，引擎回收资源的时候报错奔溃了
![飞书20220725-095356](https://user-images.githubusercontent.com/99957469/180678390-3184d81e-fead-4359-bf02-316e59768ca5.png)
这个是在场景里面加载一个带live2d的界面，然后进入游戏切出游戏，多次操作后再ui界面上更换live2d资源就出现了
![飞书20220725-095508](https://user-images.githubusercontent.com/99957469/180678394-32886377-739a-4386-9fcf-926bbb22d246.png)

**Comment by Monocluar** [comment]
现在这个问题应该没有了吧

**Comment by Jushua-bin** [comment]
是的
