### ISSUE TITLE
ui挂到场景里面会crash

### ISSUE THREAD

**Issue by Jushua-bin** [Monocluar/UnLive2D#2]
在ui里面放一个unlive2d  ui控件，然后放到场景里，游戏里面打开控制台输入memreport，必定奔溃

**Comment by Monocluar** [comment]
> 在ui里面放一个unlive2d控件，在里面放一个游戏，里面的游戏打开然后输入溃烂，跑完跑了

这个是因为一个材质GC掉了，我这里已经修复了这个问题，谢谢你的问题
