### ISSUE TITLE
奔溃crash

### ISSUE THREAD

**Issue by Jushua-bin** [Monocluar/UnLive2D#4]
建立一个空关卡，里面挂一个ui，ui上挂一个live2d控件，关闭游戏，debug版本下因为有check所以会有奔溃
![a51802a72101be41982ea40e2236701a](https://user-images.githubusercontent.com/99957469/173047033-46085085-b790-4850-99d1-08cf07dee083.png)

**Comment by Monocluar** [comment]
这个问题已经修复

**Comment by Jushua-bin** [comment]
我这边还能重现的，每次关闭游戏退出到编辑器就会出现
