### ISSUE TITLE
退出编辑器的时候会奔溃

### ISSUE THREAD

**Issue by Jushua-bin** [Monocluar/UnLive2D#6]
![6e2c5f13b79560418ca2d25611918479](https://user-images.githubusercontent.com/99957469/174579895-cbb901f3-a281-4c5f-ab22-b8fa31c58c04.png)
退出游戏回到编辑器的时候会触发奔溃

**Comment by Monocluar** [comment]
这个崩溃问题是材质没有及时回收问题
